name: check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install dependencies and build site
        run: |
          pnpm install
          pnpm run docs:build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install dependencies and run lint-md
        run: |
          pnpm install
          pnpm lint-md docs/**

      - name: Run markdownlint
        if: failure() || success()
        uses: DavidAnson/markdownlint-cli2-action@v19
