name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # 运行构建脚本
      - name: Build VuePress site
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > docs/.vuepress/dist/.nojekyll

      - uses: actions/upload-artifact@v4
        with:
          name: pages
          path: docs/.vuepress/dist/

  deploy:
    needs: [build]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        # 4.6.6无法运行 https://github.com/JamesIves/github-pages-deploy-action/issues/1698
        with:
          branch: gh-pages
          folder: dist
          token: ${{ github.token }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@master
        env:
          VERSION: ${{ github.sha }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./dist
